spring.application.name=project
server.port=${PORT:8080}

# DataSource (Aiven MySQL)
spring.datasource.url=${SPRING_DATASOURCE_HOST}?sslMode=REQUIRED
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis
mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=false