spring.application.name=project

# =========================
# DataSource (Aiven MySQL)
# =========================
spring.datasource.url=jdbc:mysql://mysql-flow-project1-flow-kimyoonho.l.aivencloud.com:18694/flowDB?sslMode=REQUIRED
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# MyBatis
# =========================
mybatis.mapper-locations=classpath:/mapper/**/*.xml
# 아래 패키지는 본인 DTO 패키지로 바꾸세요 (없으면 지워도 됨)
# mybatis.type-aliases-package=com.flow.backend.dto
mybatis.configuration.map-underscore-to-camel-case=false